### PR TITLE
Use published opentimestamps library

### PR DESCRIPTION
**Pull request by proletarius101**
This is one step closer to remove the gpmaven repo dependency, which is not guaranteed free and blocks the inclusion to F-Droid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8760#note_547751768

### CODE REVIEW

**Comment by n8fr8** [comment]
Opentimestamps dependency comes from the Proofmode library. What we need to do is move to the latest proofmode release:
https://github.com/guardianproject/proofmode/blob/master/android-libproofmode/build.gradle

which should be available via jitpack:

implementation 'com.github.guardianproject:proofmode:0.0.13-RC-3'

**Comment by proletarius101** [comment]
> com.github.guardianproject:proofmode:0.0.13-RC-3

Well, this huge. I found plenty of `Duplicate classes` errors...

**Comment by n8fr8** [comment]
Reviewing now

**Comment by n8fr8** [comment]
This is now resolved in 7f3baf18e95e618bccbe77220e41389671c12ada

**Pull request closed without merging**
