### PR TITLE
Rename "space" to "server" everywhere the user sees that word

### PR DESCRIPTION
**Pull request by neeldoshii**
Linked Issue #504 

## Description
Rename all the places where space was used and replaced it with server.
    
## Screenshots or Screencast 

Screenshot_20231012_144405

### CODE REVIEW

**Comment by foundscapes** [comment]
thanks @neeldoshii ! @tladesignz if this update works, can you make sure "server" is lowercase in the "to get started" and not "Server" (grammar). thanks!

**Comment by neeldoshii** [comment]
> thanks @neeldoshii ! @tladesignz if this update works, can you make sure "server" is lowercase in the "to get started" and not "Server" (grammar). thanks!

@foundscapes sure will make the changes and add commit. I am still unable to figure out what the project is about, I am very much interested in this project can you explain me a short summary about the project. Seems a lot of bugs in the app and degrade in performance in the app but will love to make it to next level.

**Comment by tladesignz** [comment]
Hi @neeldoshii, thanks for your contribution.
I cannot accept it, unfortunately for multiple reasons:

1. You added a typo: "derver" instead of "server"
2. You added content of a config file which you shouldn't, because it's private to your personal dev environment.
3. While changing this, I also want the string keys to become more meaningful and reflect the change. Also to make sure the translations will also make this change.

I'll take care of it myself.

Looking forward to your next contribution, though!

**Comment by neeldoshii** [comment]
> You added a typo: "derver" instead of "server"

My bad typo mistake I can change it to server on next commit. Also as a maintainer you can refactor and merge the code as I enabled maintainers to edit code. Since the code change is 1-2 lines change I think it's feasible.

> You added content of a config file which you shouldn't, because it's private to your personal dev environment.

My bad I did add it into gitignore but it messed up while commit and I didn't checked. Sorry.



> While changing this, I also want the string keys to become more meaningful and reflect the change. Also to make sure the translations will also make this change.
> 

If I am not wrong I just changed the content of the string. So if we localize to any language for example french we will just use the same string variable name and add localized language in different localized string. I didnt changed the name of string as I was not that familiar with codebase atm so I didnt wanted to break the code. 

Since the app testing is getting very difficult at this position as Opting for server is not working nor Internet Archive login working for me. 

> I'll take care of it myself.

Also just a constructive word I maybe wrong but I don't feel this right as I made the contributions but the PR gets closed and the credited work will get committed by someone else. Same happened with this #505 , #506
 
@tladesignz 

Sorry If I hurted anyone then, but as open source contributor I would liked getting credits over my work. 

@foundscapes @n8fr8 @misaakidis @mattl

**Pull request closed without merging**
