### PR TITLE
Gradle updates and cleanup

### PR DESCRIPTION
**Pull request by TacoTheDank**
### 1st commit (gradle wrapper update)
- Updated gradle wrapper to 6.7 using git bash

### 2nd commit (gradle cleanup)

- Group and clean up the build.gradle stuff to be easier to read
- Merged the pointless flavor into the buildTypes
- To use OkHttp 3.14.x we HAVE to bump minSdk to 21, otherwise anything using OkHttp in the app could quite likely crash for anyone below Lollipop (if support is wanted for versions below Lollipop, OkHttp needs to be downgraded to the 3.12.x releases), using //noinspection GradleCompatible is asking for issues. Also, you had two different minSdk versions being declared: 16 in the root ext (none of which was being used), and 19 in the app module.
- Update buildTools 28.0.3 -> 29.0.3
- Update Android Studio 3.6.3 -> 4.1.0
- Remove unused plugins
- Delete unused AndroidX legacy library
- Delete duplicate `com.amulyakhare:com.amulyakhare.textdrawable` library

### 3rd commit (library updates)
- Comment out unused libraries (no usage anywhere in code)
- Update AppCompat 1.1.0 -> 1.2.0
- Remove transitive coordinatorlayout library
- Added Multidex which was missing and causing unresolved imports
- Update Material 1.3.0-alpha01 -> 1.3.0-alpha03 ([changelog](https://github.com/material-components/material-components-android/releases))
- Updated OkHttp 3.14.0 -> 3.14.9 ([changelog](https://square.github.io/okhttp/changelog_3x/))
- Updated Okio 1.17.4 -> 2.9.0 ([changelog](https://github.com/square/okio/blob/master/CHANGELOG.md))
- Updated AppIntro 4.1.0 -> 5.1.0 ([changelog](https://github.com/AppIntro/AppIntro/releases))
- Updated CleanInsights SDK ([changelog](https://github.com/cleaninsights/cleaninsights-android-sdk/commits/master))
- Updated Picasso 2.5.2 -> 2.71828 ([changelog](https://github.com/square/picasso/blob/master/CHANGELOG.md))
- Updated Fresco 1.10.0 -> 2.3.0 ([changelog](https://github.com/facebook/fresco/releases)) (I'd honestly recommend replacing Fresco with something much lighter)
- Update circularimageview 1.4 -> 1.5 ([changelog](https://github.com/abdularis/CircularImageView/releases))
- Updated sectionedrecyclerviewadapter 2.0.0 -> 3.2.0 ([changelog](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/CHANGELOG.md))
- Updated ACRA  5.4.0 -> 5.7.0 ([changelog](https://github.com/ACRA/acra/releases))

### 4th commit (import cleanup)
- Cleaned up unused imports

### 5th commit (a bit of res cleanup)
- Remove unused resources

### 6th commit
- Fixed some missing resources causing building errors
- Fixed unresolved contexts

### CODE REVIEW

**Comment by n8fr8** [comment]
Thanks @TacoTheDank so this is a hobby of yours? I appreciate the contribution, and just noticed that you do this often for many different open-source projects. 

I think we are okay moving to minSDK 21, otherwise, yes we would need to downgrade OkHttp. Will think about that.

**Comment by TacoTheDank** [comment]
@n8fr8 Yep, pretty much. It's quite fun. A lot of the projects/apps that I contribute to are things I also use, so it's cool knowing you contributed to this thing you're using in some manner. And I learn along the way.

**Comment by TacoTheDank** [comment]
@n8fr8 Any updates?

**Comment by TacoTheDank** [comment]
Updated.

**Comment by TacoTheDank** [comment]
Oh, ok...

**Comment by n8fr8** [comment]
Thanks for the effort, but we had a developer one the team take a crack at moving these things forward.

**Comment by TacoTheDank** [comment]
Alright, thank you

**Pull request closed without merging**
