### PR TITLE
Trail-of-bits #23

### PR DESCRIPTION
**Pull request by pkhivesara**
Fixes the following issues: https://github.com/OpenArchive/OA-Trail-of-Bits/issues/23 and https://github.com/OpenArchive/OA-Trail-of-Bits/issues/21

### CODE REVIEW

**Comment by tladesignz** [comment]
Regarding #23: Patch looks fine. But OMFG. This knowledge seems completely voodoo. It's pretty hard to find a short, concise explanation on the net on what's going on there. Can you please add a short documentation what's that for and a reference to this issue, so the next person knows, why this is there, and acts accordingly? Thanks!

Regarding #21: Sorry, but it pretty much looks like you didn't read the [provided documentation](https://developer.android.com/training/articles/security-gms-provider.html#patching) or only skimmed it very briefly:

- You use the blocking `ProviderInstaller.installIfNeeded()` within `Activity.onCreate()` which is AFAIR in the UI thread. Please use this asynchronously and make sure to wait on the result before doing any networking, as explained in the docs.
- `ProviderInstaller.installIfNeeded()` might throw exceptions. You don't catch these. In case you'll switch to `installIfNeededAsync()` there's no exceptions, but different callbacks. Please handle these as per documentation.

Refer to the provided documentation on how to implement properly! Thank you!

**Comment by pkhivesara** [comment]
@tladesignz Thanks for catching that! I made the changes. But now this raises a UX issue in my mind. Do we completely block the user from using the app if they do not have the latest security update/services installed?

Or do we show some sort of messaging in the app letting them know about possible insecure HTTP call?

**Comment by tladesignz** [comment]
> Do we completely block the user from using the app if they do not have the latest security update/services installed?
> 
> Or do we show some sort of messaging in the app letting them know about possible insecure HTTP call?

Well, I'd say it's the user's decision if they want to live dangerously. So, no, don't block them, but show a permanent message.

Do you think we could add a warning bar between the header and the project bar? With a reddish background? I'd really like to have a designer at hand for problems like this... Hrm.

**Comment by pkhivesara** [comment]
> > Do we completely block the user from using the app if they do not have the latest security update/services installed?
> > Or do we show some sort of messaging in the app letting them know about possible insecure HTTP call?
> 
> Well, I'd say it's the user's decision if they want to live dangerously. So, no, don't block them, but show a permanent message.
> 
> Do you think we could add a warning bar between the header and the project bar? With a reddish background? I'd really like to have a designer at hand for problems like this... Hrm.

Isha is doing some work on UI side of things. Can ask her to help out on this. Not sure who does copy work for the app though. Putting this on the backburner until we get some UX clarification.

**Comment by pkhivesara** [comment]
Isha suggested something like below:
Screen Shot 2023-01-15 at 2 17 38 PM

**Comment by tladesignz** [comment]
> Isha suggested something like below:
> Screen Shot 2023-01-15 at 2 17 38 PM

Hmmmm. A red exclamation mark with hidden description is not exactly in your face. Not sure, if I like that. People can ignore little warning indicators pretty good. I think we should get some more thinking into this.

**Pull request merged**
