### PR TITLE
Feature/kotlin conversion phase 3

### PR DESCRIPTION
**Pull request by ozgegn**
Hi @n8fr8 ,
I implemented MVVM and WorkerManager. I created a PR for you to see new improvements. We can discuss about code here. 

PS: Please don't hurry to merge, the branch wasn't still tested :)

### CODE REVIEW

**Comment by n8fr8** [comment]
reviewing!

**Comment by n8fr8** [comment]
batch editing doesn't work as expected

1. select more than one item before they are uploaded
2. press the pencil/edit icon in the action bar
3. items are displayed in horizontal view, but the edit form is not displayed below for batch editing of fields

**Comment by n8fr8** [comment]
behavior: items remain multi selected after uploaded completes

expected: items should unselect after sent for upload / return to main screen

**Comment by n8fr8** [comment]
upload manager screen not showing anything

1. action indicator shows "5" items in queue
2. tap on number action bar item
3. "uploads" screen shows nothing in the list

**Comment by ozgegn** [comment]
Hi @n8fr8 ,
I need more detail for the comments above. Can we create a thread in Slack ?

**Comment by n8fr8** [comment]
Back on this code now, and will ping you on Slack when I have questions.

**Pull request merged**
