### PR TITLE
#566 play integrity api and dynamic features

### PR DESCRIPTION
**Pull request by ryjen**
## integrity api
- move play integrity into flavor build
- some other bug fixes with exception handling
- ignoring apps with no integrity for now, useful for proof or logging

## features
- separating the build source into 'app/src/play', the only build that will include integrity checks

- added structure to dynamically load features which can be reused by other features.  Should be a different branch, maybe with more time.

- currently features are specified in the manifest with a 'meta-data' property with the key as the class, and a value of 'feature'.

- the buildsrc manifest takes advantage of manifest merging.

- when the dynamic features are found, their koin modules are loaded, and they run 'onLoad' (or 'onUnload') with the main activity.

### CODE REVIEW

**Review by tladesignz — COMMENTED** [review]
In sincerly don't get why we would need this or why we would want this.

As per Google, these are the goals, the Play integrity API achieves:

> - Genuine app binary: Determine whether you're interacting with your unmodified binary that Google Play recognizes.

**We** are not interacting with it at all. Specific servers, that the user chooses and which are totally unrelated to us, interact with it.
I'm pretty sure, these servers are pretty oblivious to what app is actually interacting with them and in what way they might be modified or not.

> - Genuine Play install: Determine whether the current user account is licensed, which means that the user installed or paid for your app or game on Google Play.

We're not getting paid. The app is free and always will be, since American tax payers already paid for it.
We're also not interested in enforcing any user to have a valid Google account. Why would we? In fact, the opposite is true. We want *everybody* to use this app, regardless under what circumstances they have acquired it.

> - Genuine Android device: Determine whether your app is running on a genuine Android device powered by Google Play services (or a genuine instance of Google Play Games for PC).

Why would we want to help Google enforce their quasi-monopoly? In fact, we want, or at least should want the opposite: help users to free, or at least not stand in the way of freeing, their devices.

> - Free of known malware: Determine whether Google Play Protect is turned on and whether it has found risky or dangerous apps installed on the device.

Again: Why would we want to enlarge the power Google holds over its users?
While malware scanning is certainly a good idea, it should be the user's sole decision when and where to use that. **Not** ours.

It's their devices, their media, their servers. Their decisions. Not ours.

So, we add this API which enlarges Google's power over the user, which gives us nothing of value and on top of that, we invade the user's privacy by continuously leaking the app usage to Google *and* to our servers (resp. AWS or some other cloud provider) without them telling and letting them make the decision.

And we're not even gaining anything from it of worth.

**Comment by ryjen** [comment]
It is pretty simple to me: 

rooted devices can bypass encryption.

---

however I can appretiate the lack of business priority

As I did not overspend time on it honestly, if you need this branch it's there

If you don't belive me have a look at the top frida script:

https://codeshare.frida.re/browse

**Comment by tladesignz** [comment]
> rooted devices can bypass encryption.

Not phased about that at all.

There are 2 scenarios:

# User rooted device 

If a user roots their device, that's an intentional choice.
It's their device, their data, their choice.
I don't see, why we should interfere with that.

# Attack rooted device

- The media itself is outside our control anyway.
- Why should an attacker attack the Save app?
- If they, for whatever reason want to do that anyway: The code is open source. It's easy to patch the app to remove the check.

So, in that situation, the only scenario we protect against, is where an attacker installs a gadget which tries to listen in on all network traffic.
In that case, we wouldn't create that traffic, and we would be a warning sign to the user.

But if the attack is bad enough, that it would trigger Play protect, there's probably a dozen other apps, which start crying.
And we're not really protecting the user, anyway. The device already is compromised.

In case the attacker gadget would try to subvert the users submissions, that's actually the only valid reason to stop operating.

But the server configuration is open to an attacker with root. So, if they would want to create a fake submission, they could do that without the app. (or patch it, again.)


Then there's the encryption aspect:

Transport encryption doesn't defend against on-device attackers, but against network attackers. Nothing gained here.

The gain is so minimal, it's just not worth it.

**Comment by ryjen** [comment]
The use case I am concerned about is when **a user has chosen to root their device, but it is taken by persecutors** (or similar evil maid attack).

My understanding would be that if people are sharing information that they may be at physical risk for, we don't want their activity in the app to aid in persecution.

Offering your users a remote **kill switch** could be a nice option if a device is compromised.

As well, an attacker on a rooted device with the Save app installed would likely be able to obtain information on how to compromise any of the backends, and remove media.

**Comment by tladesignz** [comment]
Good point.
The intention seems good in that case, but the cure is over-boarding.

How could we make the user aware of the problem without limiting them and put them under Google control?

Is there a somewhat simple check for root we could do instead?

And then tell them on first start: 

>ATTENTION: You're running a rooted device. This might open you up for security and privacy breaches, esp. by persecution. Are you sure you want to continue?

Or a less intrusive warning (like a red bar or something in the main scene), which they don't just click out of the way?

**Comment by ryjen** [comment]
I am moving this to the private repository to cleanup.

**Pull request closed without merging**
